Create CONTRIBUTING.md with basic instructions for contributions
ivanhrabcak/cdupage pull request #12
Opened 2024-09-12 22:38 UTC by ivanhrabcak

2024-09-13 19:05 UTC, DasMatus requested changes

2024-09-13 19:05 UTC, DasMatus commented on CONTRIBUTING.md
> +I try to write code as cleanly as possible, I think readability is the most important thing when wrtiting code.
Can it be in plural, since this is a community effort?

2024-09-13 19:05 UTC, DasMatus commented on CONTRIBUTING.md
> +- ... and others, you can read the code for more information, or read the next section that describes the structure of this project, which also includes additional instructions.
This should not be here.

2024-09-13 20:02 UTC, ivanhrabcak commented on CONTRIBUTING.md
> +- ... and others, you can read the code for more information, or read the next section that describes the structure of this project, which also includes additional instructions.
What do you suggest, where should this information be?

2024-09-16 08:56 UTC, DasMatus commented on CONTRIBUTING.md
> +- ... and others, you can read the code for more information, or read the next section that describes the structure of this project, which also includes additional instructions.
As I said before, it should be shortened to "...and others", since it's obvious where to look for more information.

2024-09-16 16:34 UTC, merged